# Generated by Django 5.2.7 on 2025-10-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_lanzamiento', models.DateField()),
                ('discografica', models.CharField(max_length=255)),
                ('portada_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('paterno', models.CharField(max_length=255)),
                ('materno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('tipo_audio', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produccion.persona')),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            bases=('produccion.persona',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produccion.persona')),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField()),
            ],
            bases=('produccion.persona',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id_audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='produccion.audio')),
                ('temporada', models.IntegerField()),
                ('episodio', models.IntegerField()),
                ('duracion_extendida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Componen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.album')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Crea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('id_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.audio')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_marcado', models.DateField()),
                ('id_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.audio')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.audio')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateField()),
                ('veces_reproducido', models.IntegerField()),
                ('id_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.audio')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeReproduccion',
            fields=[
                ('id_lista_reprod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Agrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateField()),
                ('id_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.audio')),
                ('id_lista_reprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.listadereproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='produccion.audio')),
                ('numero_pista', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.album')),
            ],
        ),
    ]
